### ISSUE TITLE
Illicit Trade Stakeout

### ISSUE THREAD

**Issue by porkbob** [Kyuuhachi/Azure-Vitality#4]
Heya. So in the first quest Illicit Trade Stakeout, first off near the beginning of the quest outside IBC, Randy says "What in Genenna are you doing here?" instead of Gehenna.

The more significant issue, though, is that when you finish the quest you get 0 DP. Or if you pick the correct answer for the SSS member you chose you get 0 (+2) DP. This is true for no matter which SSS member you pick. Online resources say this quest is supposed to give 3 (+2). It's always possible they're wrong, but I have no way to know. Further, depending on what is the underlying cause this may extend to the later Evo quests as well.

Lastly, this issue is not strictly related to the quest, but I noticed inside the tar.gz you have dual nested data folders. For people not paying attention this will cause the mod to not install correctly, so probably a good idea to fix that in the next release.

Cheers, and thanks again for your efforts.

**Comment by porkbob** [comment]
An additional thing I noticed is that the quest appeared in the Intermission section of the Detective Notebook, instead of Chapter 2 where it should be. Intermission shouldn't have even appeared yet by this point.

**Comment by Kyuuhachi** [comment]
Pretty sure I fixed that one already... Must've accidentally reverted it somehow. Both the DP and the notebook section would be because I edit the quest list entry incorrectly. Will fix immediately. Thanks!
