### ISSUE TITLE
Introduction to Crossbell

### ISSUE THREAD

**Issue by porkbob** [Kyuuhachi/Azure-Vitality#5]
While you are in the conference room inside the Arseille discussing the request with Kloe (both before and after the quest proper), no music plays. Given it's a decently long time for there to be such silence, I suspect that there is something that should be playing. If you don't know what should be playing there, C.S.P.D. or The Wind from Liberl would be okay options. And yes I was on v1.1.0 for this.

Minor typo: In the conference room, Schwarz says "I believe this is an acceptable way to comply with Her Highness' wishes without unduely compromising on security" instead of 'unduly'.

Also, if you go to the Administrative district, Lloyd says "I think a lot of the citizens things of this as a place of relaxation" instead of 'thinks of this'.

Lastly, if you go to East Street, Klaudia says "I like this kind of stalls" instead of 'these kind'.

**Comment by Kyuuhachi** [comment]
Yes, you are correct; it is supposed to play *The Wind from Liberl*. I can't see any obvious reason it wouldn't be playing... It does play during the first Arseille visit... I'll have to look into this.

**Comment by Kyuuhachi** [comment]
Okay, I think I found it... Absolutely no idea *why* this happened, but here's a workaround, at least. Pretty sure it's some kind of engine bug.
