### ISSUE TITLE
Bringing Home the Bakery

### ISSUE THREAD

**Issue by porkbob** [Kyuuhachi/Azure-Vitality#8]
Didn't find anything major in the final two quests, outside of things you already listed. The only kinda awkward thing is Morges saying "I was thinking of having a sale to kick sales back into gear." It does make sense as is, but probably "I was thinking of having a sale to kick business back into gear" or ""I was thinking of doing a clearance to kick sales back into gear" would be less redundant-sounding. (I would go with the first one, myself.)

Once again, thanks for everything. Cya round!

**Comment by porkbob** [comment]
Wait, actually, now that I think of it—if the person you pick for this quest was supposed to raise their bonding score like non-evo quests where you pick a party member, it doesn't. I was one heart away from getting Noel maxed, and she is the only one who isn't maxed, so I tried to bump her up with it, but it didn't happen.

**Comment by Kyuuhachi** [comment]
Wording: good point, I'll change that. Not big enough for a new release, but I'll include it when I get around to fixing those other issues.

Bonding: no, I don't think it's supposed to give bonding points. I agree that it would make sense, but I try to keep any changes to the quests minimal.

Thanks a lot for this feedback, it helps a lot.

P.S. Are you tracking those bond points by hand, or is there some ingame way to track them that I am unaware of?

**Comment by porkbob** [comment]
In the Geofront and PH3 versions of the games, if you go into Records and scroll down to the achievements for the bonding points, you can see the little heart meters at the bottom of the screen.

**Comment by Kyuuhachi** [comment]
Oh, really? Didn't know that.
